### ISSUE TITLE
OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by fengyuentau** [drcoms/client-micropy#3]
已安装`micropython`和`micropython-lib`：
```shell
root@OpenWrt:~# opkg install micropython
Installing micropython (1.9.2-1f78e7a43130acfa4bedf16c1007a1b0f37c75c3-1) to root...
Downloading http://downloads.openwrt.org/releases/18.06.1/packages/mipsel_24kc/packages/micropython_1.9.2-1f78e7a43130acfa4bedf16c1007a1b0f37c75c3-1_mipsel_24kc.ipk
Installing libffi (3.2.1-3) to root...
Downloading http://downloads.openwrt.org/releases/18.06.1/packages/mipsel_24kc/packages/libffi_3.2.1-3_mipsel_24kc.ipk
Configuring libffi.
Configuring micropython.
root@OpenWrt:~# opkg install micropython-lib
Installing micropython-lib (1.9-f5fe55aaef1a39d3d56f07040c0ff9f7e841fdf7-1) to root...
Downloading http://downloads.openwrt.org/releases/18.06.1/packages/mipsel_24kc/packages/micropython-lib_1.9-f5fe55aaef1a39d3d56f07040c0ff9f7e841fdf7-1_mipsel_24kc.ipk
Configuring micropython-lib.
```
配置文件已经按[drcom-generic指南](https://github.com/drcoms/drcom-generic/wiki/d%E7%89%88%E7%AE%80%E7%95%A5%E4%BD%BF%E7%94%A8%E5%92%8C%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)写好并且放到了`/etc/`中。
执行`latest-wired.py`时出错：
```shell
root@OpenWrt:~# micropython latest-wired.py
Traceback (most recent call last):
  File "latest-wired.py", line 7, in <module>
  File "/usr/lib/micropython/re.py", line 6, in <module>
  File "/usr/lib/micropython/ffilib.py", line 34, in open
  File "/usr/lib/micropython/ffilib.py", line 29, in open
OSError: [Errno 2] ENOENT
```

**Comment by mchome** [comment]
已废弃，用 https://github.com/drcoms/drcom-generic 或 https://github.com/mchome/dogcom

**Comment by fengyuentau** [comment]
路由器装了openwrt之后只有4MB可用空间，不够装drcom-generic的依赖:(
https://github.com/drcoms/drcom-generic/issues/307
